name: Web UI Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    # download repo
    - uses: actions/checkout@v4

    # setup java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # install browser
    - name: Setup Chrome
    # uses: browser-actions/setup-chrome@facf10a55b9caf92e0cc749b4f82bf8220989148
      uses: browser-actions/setup-chrome@v0.0.0

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

    - name: Build with Gradle Wrapper
      run: chmod +x ./gradlew build

    # execute gradle command for running tests
    - name: Execute Test
      run: ./gradlew cucumber
